-- MySQL Script generated by MySQL Workbench
-- Fri Nov 11 08:02:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MetaViews
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS 'MetaViews' ;

-- -----------------------------------------------------
-- Schema MetaViews
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS 'MetaViews' DEFAULT CHARACTER SET utf8 ;
USE 'MetaViews' ;

-- -----------------------------------------------------
-- Table 'MetaViews'.'Usuario'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'MetaViews'.'Usuario' ;

CREATE TABLE IF NOT EXISTS 'MetaViews'.'Usuario' (
  'idUsuario' INT NOT NULL AUTO_INCREMENT,
  'email' VARCHAR(180) NOT NULL,
  'idade' INT NULL,
  'senha' VARCHAR(45) NOT NULL,
  'nome' VARCHAR(45) NOT NULL,
  PRIMARY KEY ('idUsuario'))
ENGINE = InnoDB;

CREATE UNIQUE INDEX 'idUsuario_UNIQUE' ON 'MetaViews'.'Usuario' ('idUsuario' ASC) VISIBLE;

CREATE UNIQUE INDEX 'email_UNIQUE' ON 'MetaViews'.'Usuario' ('email' ASC) VISIBLE;

CREATE UNIQUE INDEX 'nome_UNIQUE' ON 'MetaViews'.'Usuario' ('nome' ASC) VISIBLE;


-- -----------------------------------------------------
-- Table 'MetaViews'.'Avalia'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'MetaViews'.'Avalia' ;

CREATE TABLE IF NOT EXISTS 'MetaViews'.'Avalia' (
  'idUsuario' INT NOT NULL,
  'nomeMidia' VARCHAR(180) NOT NULL,
  'nota' FLOAT NOT NULL,
  PRIMARY KEY ('idUsuario'),
  CONSTRAINT 'fk_Avalia_Usuario'
    FOREIGN KEY ('idUsuario')
    REFERENCES 'MetaViews'.'Usuario' ('idUsuario')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX 'fk_Avalia_Usuario_idx' ON 'MetaViews'.'Avalia' ('idUsuario' ASC) VISIBLE;


-- -----------------------------------------------------
-- Table 'MetaViews'.'Assiste'
-- -----------------------------------------------------
DROP TABLE IF EXISTS 'MetaViews'.'Assiste' ;

CREATE TABLE IF NOT EXISTS 'MetaViews'.'Assiste' (
  'idUsuario' INT NOT NULL,
  'nomeMidia' VARCHAR(200) NOT NULL,
  PRIMARY KEY ('idUsuario'),
  CONSTRAINT 'fk_Assiste_Usuario1'
    FOREIGN KEY ('idUsuario')
    REFERENCES 'MetaViews'.'Usuario' ('idUsuario')
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
